name = "EnvironmentMigrators"
uuid = "e51d7f76-d3fb-4251-851d-1e49b8315b3e"
authors = ["Mark Kittisopikul <kittisopikulm@janelia.hhmi.org> and contributors"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
